const STAT_ABBREVIATIONS: Record<string, string> = {
  G: 'Games',
  GS: 'Games Started',
  PA: 'Plate Appearances',
  AB: 'At Bats',
  R: 'Runs',
  H: 'Hits',
  '2B': 'Doubles',
  '3B': 'Triples',
  HR: 'Home Runs',
  TB: 'Total Bases',
  RBI: 'Runs Batted In',
  BB: 'Walks',
  IBB: 'Intentional Walks',
  HBP: 'Hit By Pitch',
  SO: 'Strikeouts',
  SB: 'Stolen Bases',
  CS: 'Caught Stealing',
  SF: 'Sacrifice Flies',
  SH: 'Sacrifice Bunts',
  AVG: 'Batting Average',
  OBP: 'On-Base Percentage',
  SLG: 'Slugging Percentage',
  OPS: 'On-Base Plus Slugging',
  BABIP: 'Batting Average on Balls In Play',
  ISO: 'Isolated Power (SLG - AVG)',
  'BB%': 'Walk Percentage (BB / PA)',
  'K%': 'Strikeout Percentage (SO / PA)',
  RC: 'Runs Created',
  GPA: 'Gross Production Average',
  BIP: 'Balls In Play',
  GB: 'Ground Balls',
  LD: 'Line Drives',
  PU: 'Pop Ups',
  FB: 'Fly Balls',
  /** Hit-type grid: soft / medium / hard contact counts by batted-ball type */
  GBs: 'Ground balls (soft contact)',
  GBm: 'Ground balls (medium contact)',
  GBh: 'Ground balls (hard contact)',
  LDs: 'Line drives (soft contact)',
  LDm: 'Line drives (medium contact)',
  LDh: 'Line drives (hard contact)',
  PUs: 'Pop-ups / infield flies (soft contact)',
  PUm: 'Pop-ups (medium contact)',
  PUh: 'Pop-ups (hard contact)',
  FBs: 'Fly balls (soft contact)',
  FBm: 'Fly balls (medium contact)',
  FBh: 'Fly balls (hard contact)',
  'GB%': 'Ground Ball Percentage',
  'LD%': 'Line Drive Percentage',
  'PU%': 'Pop Up Percentage',
  'FB%': 'Fly Ball Percentage',
  W: 'Wins',
  L: 'Losses',
  SV: 'Saves',
  HLD: 'Holds',
  SVOP: 'Save Opportunities',
  BS: 'Blown Saves',
  IP: 'Innings Pitched',
  ER: 'Earned Runs',
  WP: 'Wild Pitches',
  GSc: 'Game Score',
  Kc: 'Strikeouts Looking',
  Ks: 'Strikeouts Swinging',
  GO: 'Ground Outs',
  AO: 'Air Outs',
  'GO/AO': 'Ground Out / Air Out Ratio',
  ERA: 'Earned Run Average',
  WHIP: 'Walks + Hits Per Inning Pitched',
  OBA: 'Opponent batting average (H per opponent AB; AB ≈ BF − BB − IBB − HBP)',
  FIP: 'Fielding Independent Pitching',
  'K/9': 'Strikeouts Per 9 Innings',
  'BB/9': 'Walks Per 9 Innings',
  'H/9': 'Hits Allowed Per 9 Innings',
  'FPS%': 'First-Pitch Strike Percentage',
  PO: 'Putouts',
  A: 'Assists',
  E: 'Errors',
  DP: 'Double Plays',
  TP: 'Triple Plays',
  PB: 'Passed Balls',
  SBA: 'Stolen Base Attempts',
  PK: 'Picked Off',
  'FP%': 'Fielding Percentage',
  FC: "Fielder's Choice",
  CI: "Catcher's Interference",
  GTP: 'Grounded Into Triple Play',
  B: 'Balls (pitch count)',
  BU: 'Bunt Singles',
  S: 'Strikes',
  '%S': 'Strike percentage (strikes / pitches)',
  GDP: 'Grounded Into Double Plays',
  ROE: 'Reached On Error',
  BF: 'Batters Faced',
  NP: 'Pitches thrown',
  Dec: 'Pitcher Decision',
  PIT: 'Pitches Thrown',
  Opp: 'Opponent',
  Date: 'Game Date',
  Team: 'Team',
  Player: 'Player',
  Season: 'Season',
};

export function getStatAbbreviationMeaning(label: string): string | null {
  return STAT_ABBREVIATIONS[label] ?? null;
}

