const STAT_ABBREVIATIONS: Record<string, string> = {
  G: 'Games',
  GS: 'Games Started',
  PA: 'Plate Appearances',
  AB: 'At Bats',
  R: 'Runs',
  H: 'Hits',
  '2B': 'Doubles',
  '3B': 'Triples',
  HR: 'Home Runs',
  RBI: 'Runs Batted In',
  BB: 'Walks',
  IBB: 'Intentional Walks',
  HBP: 'Hit By Pitch',
  SO: 'Strikeouts',
  SB: 'Stolen Bases',
  CS: 'Caught Stealing',
  SF: 'Sacrifice Flies',
  SH: 'Sacrifice Bunts',
  AVG: 'Batting Average',
  OBP: 'On-Base Percentage',
  SLG: 'Slugging Percentage',
  OPS: 'On-Base Plus Slugging',
  BABIP: 'Batting Average on Balls In Play',
  RC: 'Runs Created',
  GPA: 'Gross Production Average',
  BIP: 'Balls In Play',
  GB: 'Ground Balls',
  LD: 'Line Drives',
  PU: 'Pop Ups',
  FB: 'Fly Balls',
  'GB%': 'Ground Ball Percentage',
  'LD%': 'Line Drive Percentage',
  'PU%': 'Pop Up Percentage',
  'FB%': 'Fly Ball Percentage',
  W: 'Wins',
  L: 'Losses',
  SV: 'Saves',
  HLD: 'Holds',
  SVOP: 'Save Opportunities',
  BS: 'Blown Saves',
  IP: 'Innings Pitched',
  ER: 'Earned Runs',
  WP: 'Wild Pitches',
  QS: 'Quality Starts',
  CMP: 'Complete Games',
  ShO: 'Shutouts',
  GSc: 'Game Score',
  Kc: 'Strikeouts Looking',
  Ks: 'Strikeouts Swinging',
  GO: 'Ground Outs',
  AO: 'Air Outs',
  'GO/AO': 'Ground Out / Air Out Ratio',
  ERA: 'Earned Run Average',
  WHIP: 'Walks + Hits Per Inning Pitched',
  FIP: 'Fielding Independent Pitching',
  'K/9': 'Strikeouts Per 9 Innings',
  'BB/9': 'Walks Per 9 Innings',
  'H/9': 'Hits Allowed Per 9 Innings',
  PO: 'Putouts',
  A: 'Assists',
  E: 'Errors',
  DP: 'Double Plays',
  TP: 'Triple Plays',
  PB: 'Passed Balls',
  SBA: 'Stolen Base Attempts',
  PK: 'Picked Off',
  'FP%': 'Fielding Percentage',
  FC: "Fielder's Choice",
  CI: "Catcher's Interference",
  GTP: 'Grounded Into Triple Play',
  B: 'Bunt Singles',
  Dec: 'Pitcher Decision',
  Opp: 'Opponent',
  Date: 'Game Date',
  Team: 'Team',
  Player: 'Player',
  Season: 'Season',
};

export function getStatAbbreviationMeaning(label: string): string | null {
  return STAT_ABBREVIATIONS[label] ?? null;
}

